import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { VscArrowLeft, VscPlayCircle, VscGithubInverted, VscTerminal } from 'react-icons/vsc';
import './Examples.css';

const examples = [
  {
    id: 1,
    title: 'React Todo App',
    description: 'A fully functional React application built with Hooks and LocalStorage, completely generated by Groq AI in seconds.',
    tech: ['React', 'Vite', 'CSS', 'JavaScript'],
    color: '#61dafb'
  },
  {
    id: 2,
    title: 'Express REST API',
    description: 'A scalable Node.js backend with Express and Mongoose, featuring JWT Authentication and User models.',
    tech: ['Node.js', 'Express', 'MongoDB'],
    color: '#68a063'
  },
  {
    id: 3,
    title: 'Next.js Blog Platform',
    description: 'A modern, server-side rendered blog application leveraging Tailwind CSS and Markdown rendering.',
    tech: ['Next.js', 'React', 'Tailwind'],
    color: '#ffffff'
  },
  {
    id: 4,
    title: 'Python Data Analyzer',
    description: 'A Python script utilizing Pandas to read, process, and analyze large CSV data sets efficiently.',
    tech: ['Python', 'Pandas', 'Data Science'],
    color: '#3776ab'
  }
];

export default function Examples() {
  const navigate = useNavigate();

  return (
    <div className="examples-container">
      <nav className="examples-nav">
        <div className="examples-logo" onClick={() => navigate('/')}>
          <div className="logo-icon">V</div>
          <span>Vibecode</span>
        </div>
        <button className="btn btn-secondary" onClick={() => navigate('/')}>
          <VscArrowLeft /> Back to Home
        </button>
      </nav>

      <main className="examples-main">
        <motion.div 
          className="examples-header"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1>Built with Vibecode</h1>
          <p>Discover what is possible when you combine an intelligent AI agent with your creativity.</p>
        </motion.div>

        <div className="examples-grid">
          {examples.map((example, index) => (
            <motion.div 
              key={example.id}
              className="example-card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
            >
              <div className="example-visualizer">
                <div className="example-mockup">
                  <div className="example-header-dots">
                    <span className="dot red"></span>
                    <span className="dot yellow"></span>
                    <span className="dot green"></span>
                  </div>
                  <div className="example-mockup-body" style={{ borderColor: `${example.color}44` }}>
                    <VscTerminal size={48} color={example.color} style={{ opacity: 0.5 }} />
                  </div>
                </div>
              </div>
              
              <div className="example-content">
                <h2>{example.title}</h2>
                <p>{example.description}</p>
                
                <div className="example-tags">
                  {example.tech.map(tech => (
                    <span key={tech} className="example-tag">{tech}</span>
                  ))}
                </div>

                <div className="example-actions">
                  <button className="btn btn-primary btn-sm">
                    <VscPlayCircle size={16} /> Try it
                  </button>
                  <button className="btn btn-secondary btn-sm">
                    <VscGithubInverted size={16} /> View Code
                  </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </main>
    </div>
  );
}
